Aeris catalogue draw map button
aeris-data/aeris-catalogue-components-vjs pull request #10
Opened 2019-02-20 12:57 UTC by samirboumaza

2019-02-27 09:41 UTC, esteban-em requested changes
Dans `data` : `aerisSpatialExtentMapModeListener: null,`, `themevalue: null,` et `iconThemeValue: null` ne sont pas utilisés.

2019-02-27 09:41 UTC, esteban-em commented on src/lib/modules/aeris-catalog-buttons/aeris-catalogue-draw-map-button/components/aeris-catalogue-draw-map-button.vue
> +        return {};
Tu peux réécrire ça sans le `else` : 

```js
    getTheme() {
      if (this.isActive) {
        return {
          emphasis: "#f39c12",
          color: "grey"
        };
      }
      return {};
    },
```

Ou même comme ça : 

```js
    getTheme() {
      return this.isActive ? { emphasis: "#f39c12", color: "grey" } : {};
    },
```

2019-02-27 09:41 UTC, esteban-em commented on src/lib/modules/aeris-catalog-buttons/aeris-catalogue-draw-map-button/components/aeris-catalogue-draw-map-button.vue
>      getThemeIcon() {
Idem, tu peux réécrire ça comme ça : 

```js
getThemeIcon() {
    return this.isActive ? { color: "white" } : { color: "white" };
},
```

Mais je m'aperçois que c'est toujours `white`, c'est normal ?

Dans ce cas, même pas besoin de fonction en fait.

2019-02-27 10:12 UTC, vlhung commented on src/lib/modules/aeris-catalog-buttons/aeris-catalogue-draw-map-button/components/aeris-catalogue-draw-map-button.vue
> +      aerisSpatialExtentMapModeListener: null,
tu as oublié de l'enlever :-)

2019-02-27 10:17 UTC, vlhung commented
Il faudrait également réorganiser selon les modules pour src/demo de ce composant :-)

2019-03-05 13:22 UTC, esteban-em approved these changes

2019-03-08 15:03 UTC, merged