Aeris catalogue help button
aeris-data/aeris-catalogue-components-vjs pull request #11
Opened 2019-02-20 12:58 UTC by samirboumaza

2019-02-27 09:31 UTC, esteban-em requested changes
Un `function()` qui traine

2019-02-27 12:41 UTC, vlhung commented on src/demo/components/aeris-catalogue-help-button-test.vue
> +    <aeris-catalogue-help-button :theme="theme" @AskForHelp="visible = !visible" lang="en"></aeris-catalogue-help-button>
language :-)

2019-02-27 12:41 UTC, vlhung commented on src/lib/modules/aeris-catalog-buttons/aeris-catalogue-help-button/components/aeris-catalogue-help-button.vue
>      }
askForHelp?

2019-02-27 12:41 UTC, vlhung commented on src/demo/components/aeris-catalogue-help-button-test.vue
> +    <aeris-catalogue-help-button :theme="theme" @AskForHelp="visible = !visible" lang="en"></aeris-catalogue-help-button>
askForHelp?

2019-03-04 13:44 UTC, vlhung commented on src/demo/app.vue
> +        <router-link to="/search_box">/serach box</router-link>
à enlever car ce lien existe déjà :-)

2019-03-04 13:44 UTC, vlhung commented on src/demo/modules/aeris-catalog-button/aeris-catalogue-help-button/aeris-catalogue-help-button-test.vue
> +    <aeris-catalogue-help-button :theme="theme" @askForHelp="visible = !visible" lang="en"></aeris-catalogue-help-button>
tu as oublié de modifier lang en language :-)

2019-03-08 15:18 UTC, vlhung approved these changes

2019-03-08 15:18 UTC, merged