Aeris catalogue maximize button
aeris-data/aeris-catalogue-components-vjs pull request #12
Opened 2019-02-20 12:58 UTC by samirboumaza

2019-02-27 09:01 UTC, esteban-em requested changes
`computeTitle: function()`

PS : je te mets un point pour la ref à Aladdin :+1: :wink:

2019-02-27 13:00 UTC, vlhung reviewed
Il y a également un oubli de changer l'ordre des props d'un composant vue :-)

2019-02-27 13:00 UTC, vlhung commented on src/demo/components/aeris-catalogue-maximize-button-test.vue
> +      lang="en"
language? :-D

2019-02-27 13:00 UTC, vlhung commented on src/lib/modules/aeris-catalog-buttons/aeris-catalogue-maximize-button/components/aeris-catalogue-maximize-button.vue
> +        this.$emit("CatalogueMinimize");
catalogueMinimize / catalogueMinimize ? :-)

2019-03-04 13:40 UTC, vlhung commented on src/demo/app.vue
> +        <router-link to="/search_box">/search box</router-link>
ce lien existe déjà :)

2019-03-06 10:10 UTC, esteban-em approved these changes

2019-03-11 09:58 UTC, merged