Aeris catalogue reset button
aeris-data/aeris-catalogue-components-vjs pull request #13
Opened 2019-02-20 13:00 UTC by samirboumaza

2019-02-27 08:58 UTC, esteban-em requested changes
Idem que pour reset-text-button : le bloc `data` n'est pas utilisé.

Et il y a deux `function()` qui trainent ;)

2019-02-27 13:04 UTC, vlhung reviewed
pareil qu'ici, un oubli d'ordre des props d'un composant vue :-)

2019-02-27 13:04 UTC, vlhung commented on src/demo/components/aeris-catalogue-reset-button-test.vue
> +      <aeris-catalogue-reset-button lang="en" :theme="theme" @CatalogueReset="visible= !visible"></aeris-catalogue-reset-button>
language :-)

2019-02-27 13:04 UTC, vlhung commented on src/lib/modules/aeris-catalog-buttons/aeris-catalogue-reset-button/components/aeris-catalogue-reset-button.vue
> +      this.$emit("CatalogueReset");
catalogueReset? :-)

2019-03-05 13:16 UTC, esteban-em commented
> Idem que pour reset-text-button : le bloc `data` n'est pas utilisé.
> 
> Et il y a deux `function()` qui trainent ;)

Il reste un `function` et le bloc `data` qui ne sert à rien

2019-03-06 10:11 UTC, esteban-em approved these changes

2019-03-11 10:15 UTC, merged