Aeris catalogue reset text button
aeris-data/aeris-catalogue-components-vjs pull request #14
Opened 2019-02-20 13:01 UTC by samirboumaza

2019-02-27 08:56 UTC, esteban-em requested changes

2019-02-27 08:56 UTC, esteban-em commented on src/lib/modules/aeris-catalog-buttons/aeris-catalogue-reset-text-button/components/aeris-catalogue-reset-text-button.vue
bloc `data` à enlever car pas utilisé

2019-02-27 13:08 UTC, vlhung reviewed
l'ordre des props d'un composant vue :-)

2019-02-27 13:08 UTC, vlhung commented on src/demo/components/aeris-catalogue-reset-text-button-test.vue
> +        <aeris-catalogue-reset-text-button :theme="theme" lang="en" @CatalogueReset="visible=!visible"></aeris-catalogue-reset-text-button>
language

2019-02-27 13:08 UTC, vlhung commented on src/lib/modules/aeris-catalog-buttons/aeris-catalogue-reset-text-button/components/aeris-catalogue-reset-text-button.vue
> +      this.$emit("CatalogueReset");
catalogueReset? :-)

2019-03-04 15:01 UTC, vlhung approved these changes

2019-03-04 15:04 UTC, merged