Aeris catalogue search text button
aeris-data/aeris-catalogue-components-vjs pull request #15
Opened 2019-02-20 13:01 UTC by samirboumaza

2019-02-27 08:52 UTC, esteban-em reviewed
Quelques trucs sont mal indentés il me semble. 
Il y a une erreur à résoudre quand on run `npm run format`.
Sinon ça me paraît okay :+1:

2019-02-27 13:13 UTC, vlhung commented on src/lib/modules/aeris-catalog-buttons/aeris-catalogue-search-text-button/components/aeris-catalogue-search-text-button.vue
> +      this.$emit("CatalogueSearchStart",0,24)
catalogueSearchStart? :-)
vaut il mieux avoir un object avec min et max ou un retour avec 2 paramètres?

2019-03-04 08:31 UTC, samirboumaza commented on src/lib/modules/aeris-catalog-buttons/aeris-catalogue-search-text-button/components/aeris-catalogue-search-text-button.vue
> +      this.$emit("CatalogueSearchStart",0,24)
catalogueSearchStart parce que c'est le nom de l'event d'origine

2019-03-04 13:49 UTC, vlhung commented on src/demo/main.js
> +   aeris-catalogue-search-text-button
petit problème avec les accolades etc :-P

2019-03-04 13:49 UTC, vlhung commented on src/lib/modules/aeris-catalog-buttons/aeris-catalogue-search-text-button/components/aeris-catalogue-search-text-button.vue
> +      this.$emit("CatalogueSearchStart",this.range)
modifier CatalogueSearchStart en catalogueSearchStart? :-)

2019-03-06 10:14 UTC, esteban-em requested changes

2019-03-06 10:14 UTC, esteban-em commented on src/demo/main.js
> +<<<<<<< HEAD
t'as commité sans résoudre le conflit :rofl:

2019-03-07 08:56 UTC, esteban-em commented on src/demo/main.js
>        component : AerisCatalogueSearchTextButtontest
Le fichier n'est pas linté ^^'

2019-03-08 08:41 UTC, esteban-em approved these changes

2019-03-11 10:25 UTC, merged