Aeris catalogue map
aeris-data/aeris-catalogue-components-vjs pull request #18
Opened 2019-02-21 08:50 UTC by vlhung

2019-02-27 10:31 UTC, vlhung commented
comment comptes tu gérer les customs events restants dans map?

2019-02-27 10:33 UTC, esteban-em requested changes
- fonction `handleSearchBarSearchEvent()` pas utilisée
- `<style scoped>`
- la classe css `.viewport` n'existe pas : supprimer les styles `[data-aeris-catalog-map] .viewport`
- idem pour `.map.reduced`
- styles `[data-aeris-catalog-map] aeris-spinner` à supprimer aussi
- idem pour `.feature-info-tooltip` (4 blocs de style à supprimer)

2019-02-27 10:33 UTC, esteban-em commented on src/lib/modules/aeris-catalog-map/components/aeris-catalog-map.vue
>    name: "aeris-catalog-map",
Utiliser des noms de fichier cohérent avec le nom des composants : ici il faudraitque tout s'appelle `aeris-catalogue-map` (comme dans le test.vue). Donc :
- changer le nom de fichier `aeris-catalog-map.vue` en `aeris-catalogue-map.vue`
- changer le nom du composant "aeris-catalog-map" en "aeris-catalogue-map"

2019-02-27 10:33 UTC, esteban-em commented on src/lib/modules/aeris-catalog-map/components/aeris-catalog-map.vue
> +import * as extent from "ol/extent";
- `extent` n'est pas utilisé d'après mon éditeur
- `Modify`, `Snap` `OSM` et `Circle` non plus apparemment

2019-02-27 10:33 UTC, esteban-em commented on src/lib/modules/aeris-catalog-map/components/aeris-catalog-map.vue
>        type: Boolean,
`visible` à supprimer

2019-02-27 10:33 UTC, esteban-em commented on src/lib/modules/aeris-catalog-map/components/aeris-catalog-map.vue
> +      ol: null,
`ol` pas utilisé

2019-02-27 10:33 UTC, esteban-em commented on src/lib/modules/aeris-catalog-map/components/aeris-catalog-map.vue
> +      let _this = this;
`_this` n'est pas utilisé

2019-02-27 10:33 UTC, esteban-em commented on src/lib/modules/aeris-catalog-map/components/aeris-catalog-map.vue
> +      let id = "selectionBox";
ligne à supprimer

2019-03-26 07:38 UTC, esteban-em requested changes
Chez moi les icônes ne sont pas centrées dans les boutons de la carte

2019-03-26 07:38 UTC, esteban-em commented on src/demo/modules/aeris-catalog-layouts/aeris-search-criteria-layout/aeris-catalogue-search-box-test.vue
> +<<<<<<< HEAD
c'est tout pas beau :eyes:

2019-03-27 09:52 UTC, esteban-em commented
Il faut juste enlever le `margin-right: 10px;` dans **aeris-commons** : 

```css
.button i {
  margin-right: 10px;
}
```

Et pour l'espacement entre les boutons : 

```css
.button > *:last-child {
  margin-left: 10px;
}
```

2019-03-27 12:42 UTC, esteban-em approved these changes

2019-03-27 13:03 UTC, merged