refactor(aeris-catalog-help-content): refactoring
aeris-data/aeris-catalogue-components-vjs pull request #24
Opened 2019-03-05 13:43 UTC by ttdev2toulouse

2019-03-05 16:51 UTC, esteban-em requested changes

2019-03-05 16:51 UTC, esteban-em commented on src/demo/modules/aeris-catalog-help-content-test.vue
> +  <div>
pas besoin des  `<div>` vu qu'il n'y a qu'un enfant

2019-03-05 16:51 UTC, esteban-em commented on src/demo/modules/aeris-catalog-help-content-test.vue
> +  data() {
tu peux enlever le bloc `data` s'il n'est pas utilisé.

2019-03-05 16:51 UTC, esteban-em commented on src/lib/modules/aeris-catalog-help/components/aeris-catalog-help-content.vue
>      this.aerisThemeListener = this.handleTheme.bind(this);
événements à enlever et à gérer autrement

2019-03-05 16:51 UTC, esteban-em commented on src/lib/modules/aeris-catalog-help/components/aeris-catalog-help-content.vue
>        var d = new Date();
Il y a des `var` qui trainent un peu partout ^^

2019-03-08 08:47 UTC, esteban-em reviewed
Le bouton "do not display" a des marges un peu bizarre, non ? En haut et à droite. Du coup il n'est pas vraiment centré. Mais je ne sais pas ce que ça doit donner au final.

2019-03-11 16:43 UTC, esteban-em requested changes

2019-03-11 16:43 UTC, esteban-em commented on src/lib/modules/aeris-catalog-help/components/aeris-catalog-help-content.vue
> -.popup-content,
si tu ne t'en sert plus, tu peux les enlever du template aussi

2019-03-26 10:27 UTC, vlhung approved these changes

2019-03-26 10:27 UTC, merged