Metadata panel
aeris-data/aeris-catalogue-components-vjs pull request #25
Opened 2019-03-18 12:36 UTC by samirboumaza

2019-03-20 13:56 UTC, vlhung requested changes

2019-03-20 13:56 UTC, vlhung commented on src/demo/modules/aeris-metadata-panel/metadata-panel-test.vue
> +      currentPlatformType: null,
pas utilisé

2019-03-20 13:56 UTC, vlhung commented on src/demo/modules/aeris-metadata-panel/metadata-panel-test.vue
> +      project: null,
pas utilisé

2019-03-20 13:56 UTC, vlhung commented on src/demo/modules/aeris-metadata-panel/metadata-panel-test.vue
> +      currentIconClass: null,
pas utilisé

2019-03-20 13:56 UTC, vlhung commented on src/lib/modules/aeris-catalog-layouts/aeris-metadata-template/components/md-template-collection.vue
> +    <aeris-metadata-quicklook-gallery :language="language" :theme="theme"></aeris-metadata-quicklook-gallery>
il manque :quicklooks="metadata.quicklooks"

2019-03-20 13:56 UTC, vlhung commented on src/lib/modules/aeris-catalog-layouts/aeris-metadata-template/components/md-template-collection.vue
> +    getOtherInformations() {
non utilisé

2019-03-20 13:56 UTC, vlhung commented on src/lib/modules/aeris-catalog-layouts/aeris-metadata-template/components/md-template-proxy.vue
>      contenu: function() {
pas utilisé

2019-03-20 13:56 UTC, vlhung commented on src/lib/modules/aeris-catalog-layouts/aeris-metadata-template/components/md-template-proxy.vue
>      elementName() {
pas utilisé

2019-03-20 13:56 UTC, vlhung commented on src/lib/modules/aeris-catalog-layouts/aeris-metadata-template/components/md-template-proxy.vue
> +    console.log("metadata proxy: ", this.metadata);
quelques console.log

2019-03-20 13:56 UTC, vlhung commented on src/lib/modules/aeris-catalog-layouts/aeris-metadata-template/components/md-template-proxy.vue
>        templateVueComponents: [
pas utilisé

2019-03-20 13:56 UTC, vlhung commented on src/demo/modules/aeris-metadata-panel/metadata-panel-test.vue
> +          :metadata="currentMetadata"
je pense que c'est plutôt summary au lieu de metadata afin de ne pas confondre avec les metadata que l'on récupère en cliquant sur un des "summaries".
En passant summary dans aeris-catalogue-metadata-panel, il n'y a plus besoin des props resourcetitle, uuid, type, clientTemplate, projects

2019-03-20 13:56 UTC, vlhung commented on src/lib/modules/aeris-catalog-metadata-panel/components/aeris-catalog-metadata-panel.vue
> +      if (true) {
toujours vrai :-P

2019-03-20 13:56 UTC, vlhung commented on src/lib/modules/aeris-catalog-metadata-panel/components/aeris-catalog-metadata-panel.vue
> +      if (this.type === "COLLECTION") {
tu voulais dire !== à mon avis

2019-03-25 07:56 UTC, samirboumaza commented on src/lib/modules/aeris-catalog-layouts/aeris-metadata-template/components/md-template-proxy.vue
> +    console.log("metadata proxy: ", this.metadata);
en fait il ne sert plus a rien celui la

2019-03-25 12:39 UTC, samirboumaza commented on src/demo/modules/aeris-metadata-panel/metadata-panel-test.vue
> +          :metadata="currentMetadata"
en fait on en a plus besoin ^^

2019-03-25 12:53 UTC, vlhung commented on src/demo/modules/aeris-metadata-panel/metadata-panel-test.vue
> +          :metadata="currentMetadata"
je pense que c'est mieux d'utiliser un seul summary comme props qu'utiliser pleins de props (uuid, type, resourcetitle etc) :-)
 tu t'es laissé piégé par l'ancien code :-D

2019-03-25 16:04 UTC, vlhung approved these changes

2019-03-25 16:05 UTC, merged