Aeris catalog criteria temporal search criteria
aeris-data/aeris-catalogue-components-vjs pull request #27
Opened 2019-03-20 15:08 UTC by ttdev2toulouse

2019-03-25 11:37 UTC, vlhung requested changes
Il faudrait également ajouter un store pour pouvoir récupérer et réinitialiser les dates

2019-03-25 11:37 UTC, vlhung commented on src/demo/modules/aeris-catalog-criteria/aeris-search-criteria/aeris-temporal-search-criteria-test.vue
> +  <aeris-temporal-search-criteria lang="en"></aeris-temporal-search-criteria>
language? :-)

2019-03-25 11:37 UTC, vlhung commented on src/lib/modules/aeris-catalog-criteria/aeris-search-criteria/aeris-temporal-search-criteria/components/aeris-temporal-search-criteria-content.vue
plus besoin de i18n ici, tu peux le supprimer

2019-03-25 11:37 UTC, vlhung commented on src/lib/modules/aeris-catalog-criteria/aeris-search-criteria/aeris-temporal-search-criteria/components/aeris-temporal-search-criteria-content.vue
> +      language="fr"
toujours fr? :-)

2019-03-25 11:37 UTC, vlhung commented on src/lib/modules/aeris-catalog-criteria/aeris-search-criteria/aeris-temporal-search-criteria/components/aeris-temporal-search-criteria-content.vue
> +      language="fr"
toujours fr? :-)

2019-03-25 11:37 UTC, vlhung commented on src/lib/modules/aeris-catalog-criteria/aeris-search-criteria/aeris-temporal-search-criteria/components/aeris-temporal-search-criteria-content.vue
> +      default: "fr"
default en? :-D

2019-03-25 11:37 UTC, vlhung commented on src/lib/modules/aeris-catalog-criteria/aeris-search-criteria/aeris-temporal-search-criteria/components/aeris-temporal-search-criteria-content.vue
>      lang: {
language

2019-03-25 11:37 UTC, vlhung commented on src/lib/modules/aeris-catalog-criteria/aeris-search-criteria/aeris-temporal-search-criteria/components/aeris-temporal-search-criteria-content.vue
>      <span v-if="errorMessage" class="error-message">{{ errorMessage }}</span>
errorMessage n'est plus utilisé

2019-03-25 11:37 UTC, vlhung commented on src/lib/modules/aeris-catalog-criteria/aeris-search-criteria/aeris-temporal-search-criteria/components/aeris-temporal-search-criteria-content.vue
> +      dateFormat: "DD/MM/YYYY HH:mm:ss",
ce n'est plus utilisé

2019-03-25 11:37 UTC, vlhung commented on src/lib/modules/aeris-catalog-criteria/aeris-search-criteria/aeris-temporal-search-criteria/components/aeris-temporal-search-criteria-content.vue
> +      dateFormat: "DD/MM/YYYY HH:mm:ss",
pareil pour from, to, errorMessage

2019-03-25 11:37 UTC, vlhung commented on src/lib/modules/aeris-catalog-criteria/aeris-search-criteria/aeris-temporal-search-criteria/components/aeris-temporal-search-criteria-content.vue
> +    handleSearch(e) {
cette fonction n'est plus utilisée

2019-03-25 11:37 UTC, vlhung commented on src/lib/modules/aeris-catalog-criteria/aeris-search-criteria/aeris-temporal-search-criteria/components/aeris-temporal-search-criteria-content.vue
> +    handleCatalogueReset() {
cette fonction n'est plus utilisée

2019-03-25 11:37 UTC, vlhung commented on src/lib/modules/aeris-catalog-criteria/aeris-search-criteria/aeris-temporal-search-criteria/components/aeris-temporal-search-criteria.vue
> +      <aeris-temporal-search-criteria-content lang="fr"></aeris-temporal-search-criteria-content>
language?
l'affectation soit plus générique? :-)

2019-03-25 11:37 UTC, vlhung commented on src/lib/modules/aeris-catalog-criteria/aeris-search-criteria/aeris-temporal-search-criteria/components/aeris-temporal-search-criteria.vue
>      lang: {
language

2019-03-25 11:37 UTC, vlhung commented on src/lib/modules/aeris-catalog-criteria/aeris-search-criteria/aeris-temporal-search-criteria/components/aeris-temporal-search-criteria.vue
> +      default: "fr"
default : "en"

2019-03-25 11:39 UTC, vlhung commented on src/lib/modules/aeris-catalog-criteria/aeris-search-criteria/aeris-temporal-search-criteria/components/aeris-temporal-search-criteria-content.vue
> +    handleCatalogueReset() {
il y a également des styles déclarés et pas utilisés

2019-03-26 07:50 UTC, esteban-em requested changes
**[edit]** En fait, c'est les traductions qui ne sont pas prises en compte. À investiguer quand même du coup ^^

Le mois est affiché en minuscule. À investiguer...

2019-03-26 07:50 UTC, esteban-em commented on src/lib/modules/aeris-catalog-criteria/aeris-search-criteria/aeris-temporal-search-criteria/components/aeris-temporal-search-criteria-content.vue
> +<style scoped>
- Tous les styles avec `.aeris-input-group` ne sont pas utilisés.
- `.right` n'est pas utilisé non plus

2019-03-28 15:33 UTC, merged