Aeris catalog
aeris-data/aeris-catalogue-components-vjs pull request #30
Opened 2019-03-28 16:17 UTC by vlhung

2019-03-29 08:32 UTC, esteban-em commented on src/demo/app.vue
> +        <router-link to="/catalog-cart">/catalog cart</router-link>
`/catalog-cart` en double :stuck_out_tongue_winking_eye:

2019-04-01 07:01 UTC, esteban-em requested changes
La **touche `entrée`** pour la recherche ne fonctionne plus

2019-04-01 07:01 UTC, esteban-em commented on src/lib/modules/aeris-catalog-criteria/aeris-search-criteria/aeris-keyword-search-criteria/components/aeris-keyword-search-criteria.vue
> +  created: function() {
`function ()` :stuck_out_tongue:

2019-04-01 07:01 UTC, esteban-em commented on src/lib/modules/aeris-catalog-criteria/aeris-search-criteria/aeris-keyword-search-criteria/components/aeris-keyword-search-criteria.vue
> +<style>
manque le `scoped` ?

2019-04-01 07:01 UTC, esteban-em commented on src/lib/modules/aeris-catalog-layouts/aeris-search-criteria-layout/components/aeris-catalog-search-box.vue
>    position: relative;
prop `boxTitle` pas utilisée

2019-04-01 07:01 UTC, esteban-em commented on src/lib/modules/aeris-catalog/aeris-catalog.vue
- bloc `data` pas utilisé
- méthode `startSearch`  pas utilisée
- méthode `resetSearch`  pas utilisée

2019-04-02 14:32 UTC, esteban-em requested changes
- J'ai une notification `No criteria selected` quand je tape un truc dans la barre de recherche et que je la lance
- La touche `Entrée` ne fonctionne toujours pas

2019-04-02 14:57 UTC, vlhung commented
> * J'ai une notification `No criteria selected` quand je tape un truc dans la barre de recherche et que je la lance
> * La touche `Entrée` ne fonctionne toujours pas

J'ai fait une mise à jour de commons pour ui-input, je pense qu'il faudrait récupérer la dernière version de commons pour que ça marche :-)

2019-04-03 07:13 UTC, esteban-em commented
Okay ça marche ! :+1: 

Il faudrait vérifier s'il n'y a pas une commande pour "refresh" le package.json pour les repos git pour ne pas avoir à tout télécharger à chaque fois.

2019-04-08 10:18 UTC, merged