Scrollbar
aeris-data/aeris-catalogue-components-vjs pull request #36
Opened 2019-06-13 09:32 UTC by esteban-em

2019-06-13 13:15 UTC, samirboumaza approved these changes

2019-06-28 10:33 UTC, vlhung requested changes
Je pense que le scrollbar dont parlait Damien ou Guillaume, c'est celui qui se trouve toute à droite, ça concerne toute la page. Le scrollbar pour la liste des summaries est très bien, je ne crois pas que l'on ait besoin de l'enlever. Exemple site actuel https://www.aeris-data.fr/catalogue/ et site test https://www7.obs-mip.fr/test/catalogue/ :-)

2019-07-01 08:21 UTC, esteban-em commented
> Je pense que le scrollbar dont parlait Damien ou Guillaume, c'est celui qui se trouve toute à droite, ça concerne toute la page. Le scrollbar pour la liste des summaries est très bien, je ne crois pas que l'on ait besoin de l'enlever. Exemple site actuel https://www.aeris-data.fr/catalogue/ et site test https://www7.obs-mip.fr/test/catalogue/ :-)

Oui, j'ai bien compris. Je n'ai pas changé le comportement du scrollbar des summaries. Ça marche pas chez toi ?

2019-07-01 08:25 UTC, vlhung commented
> > Je pense que le scrollbar dont parlait Damien ou Guillaume, c'est celui qui se trouve toute à droite, ça concerne toute la page. Le scrollbar pour la liste des summaries est très bien, je ne crois pas que l'on ait besoin de l'enlever. Exemple site actuel https://www.aeris-data.fr/catalogue/ et site test https://www7.obs-mip.fr/test/catalogue/ :-)
> 
> Oui, j'ai bien compris. Je n'ai pas changé le comportement du scrollbar des summaries. Ça marche pas chez toi ?

D'accord, car je n'ai plus de scrollbar sur la liste des summaries du coup je me suis dit que tu as du l'enlever :-P

2019-07-01 09:24 UTC, vlhung approved these changes

2019-07-01 09:27 UTC, merged