refactor(aeris-international-field): refactoring
aeris-data/aeris-catalogue-components-vjs pull request #8
Opened 2019-02-20 09:30 UTC by ttdev2toulouse

2019-02-26 16:27 UTC, esteban-em requested changes
Pense aussi à ajouter `scoped` à la balise `<style>`.

Et saute peut-être une ligne entre les blocs `<i18n>` et `<template>`.

2019-02-26 16:27 UTC, esteban-em commented on src/lib/modules/aeris-international-field/components/aeris-international-field.vue
> +      console.log("value :", this.value)
`console.log` à enlever

2019-02-26 16:27 UTC, esteban-em commented on src/lib/modules/aeris-international-field/components/aeris-international-field.vue
> +       console.log("value json :",JSON.parse(this.value))
là aussi `console.log`

2019-02-26 16:27 UTC, esteban-em commented on src/lib/modules/aeris-international-field/components/aeris-international-field.vue
>        var json = JSON.parse(this.value);
`var` à remplacer par `let` ou même `const` (si la variable n'est pas modifiée par la suite)

2019-02-26 16:27 UTC, esteban-em commented on src/lib/modules/aeris-international-field/components/aeris-international-field.vue
>        for (var key in json) {
remplacer `var` par `let`

2019-02-26 16:27 UTC, esteban-em commented on src/lib/modules/aeris-international-field/components/aeris-international-field.vue
> +      console.log(value)
`console.log`

2019-02-27 12:22 UTC, vlhung commented on src/demo/components/aeris-international-field-test.vue
> +      value: "{\"en\" : \"**Amsterdam Island** is a small island (55km2) located in the southern Indian Ocean (37◦48 S, 77◦34 E), 3400km and 5000km downwind from the nearest lands, Madagascar and Sou
doit être de type Object au lieu de String

2019-02-27 12:22 UTC, vlhung commented on src/lib/modules/aeris-international-field/components/aeris-international-field.vue
>    props: {
prop value doit être de type Object

2019-02-27 12:22 UTC, vlhung commented on src/lib/modules/aeris-international-field/components/aeris-international-field.vue
> +      console.log(value)
<style scoped>

2019-02-27 12:22 UTC, vlhung commented on src/lib/modules/aeris-international-field/components/aeris-international-field.vue
> +    truncate(value) {
méthode truncate peut être simplifiée

2019-02-27 12:22 UTC, vlhung commented on src/lib/modules/aeris-international-field/components/aeris-international-field.vue
> +    text() {
méthode text() peut être simplifiée

2019-03-06 15:24 UTC, esteban-em approved these changes

2019-03-08 13:00 UTC, merged