Aeris catalogue search button
aeris-data/aeris-catalogue-components-vjs pull request #9
Opened 2019-02-20 12:57 UTC by samirboumaza

2019-02-27 09:44 UTC, esteban-em requested changes
Il y a un deuxième bloc `data` et il ne sert à rien :smile:

2019-02-27 09:44 UTC, esteban-em commented on src/lib/modules/aeris-catalog-buttons/aeris-catalogue-search-button/components/aeris-catalogue-search-button.vue
>  </template>
et si on sautait une ligne entre le `<template>` et `<script>` ? :stuck_out_tongue:

2019-02-27 09:44 UTC, esteban-em commented on src/lib/modules/aeris-catalog-buttons/aeris-catalogue-search-button/components/aeris-catalogue-search-button.vue
> +  data() {
bloc `data` à supprimer

2019-02-27 09:44 UTC, esteban-em commented on src/lib/modules/aeris-catalog-buttons/aeris-catalogue-search-button/components/aeris-catalogue-search-button.vue
> +
ligne vide à supprimer

2019-02-27 12:33 UTC, vlhung commented on src/lib/modules/aeris-catalog-buttons/aeris-catalogue-search-button/components/aeris-catalogue-search-button.vue
>    data() {
data() avant watch ():-P

2019-02-27 12:33 UTC, vlhung commented on src/lib/modules/aeris-catalog-buttons/aeris-catalogue-search-button/components/aeris-catalogue-search-button.vue
> +      this.$emit("CatalogueSearchStart", 0,24);
nom d'un événement commence toujours par un minuscule? (je ne sais plus si on en a déjà parlé)

2019-03-04 09:18 UTC, samirboumaza commented on src/lib/modules/aeris-catalog-buttons/aeris-catalogue-search-button/components/aeris-catalogue-search-button.vue
>  </template>
c'est une idée à creuser :p

2019-03-04 09:21 UTC, samirboumaza commented on src/lib/modules/aeris-catalog-buttons/aeris-catalogue-search-button/components/aeris-catalogue-search-button.vue
> +      this.$emit("CatalogueSearchStart", 0,24);
je m'en souvenais plus mais je voulais a un moment qu'on prenne un moment pour normaliser ces nom justement :p

2019-03-04 13:15 UTC, vlhung reviewed
juste un lien en trop <router-link to="//search_box">/search box</router-link>
après ça c'est bon pour le merge :)

2019-03-04 13:15 UTC, vlhung commented on src/demo/app.vue
> +        <router-link to="//search_box">/search box</router-link>
à enlever, ce lien existe déjà :-)

2019-03-04 15:12 UTC, vlhung approved these changes

2019-03-04 15:12 UTC, merged

2019-03-05 13:19 UTC, esteban-em commented
> Il y a un deuxième bloc `data` et il ne sert à rien smile

Il y a toujours le bloc `data` qui ne sert à rien